site_name: diabetic
repo_url: https://github.com/nttda328/diabetic
docs_dir: mkdocs
site_dir: docs
theme:
  name: material
  palette:
    primary: blue
    accent: blue
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - mkdocs/gen_ref_page.py
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_signature: False
            heading_level: 1
      watch:
        - diabetic/
        - serving/
        - README.md

nav:
    - Home: index.md
    - Dag : dag.md
    - Tasks: tasks.md
    - Flows: flows.md
    - Serve Model : serving.md